### PR TITLE
Separate denominator from display format.

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

The current implementation uses denominator for both computing KeyMetric/Hightlight format as well as displaying the value to the user on the front-end. This complicates issues for example when you have an absolute_value that you want to be displayed as a percentage.

This PR introduces display_format to allow the profile administrators the ability to customize how the value should be displayed regardless of how they were computed.

## Screenshot

Screenshot from 2022-05-27 09-50-08

## Checklist

- [x]  🚀 is the code ready to be merged and go live?
- [x]  🛠 does it work (build) locally

### CODE REVIEW

**Review by esirK — APPROVED** [review]
Looks all good @kilemensi 
But maybe we could add a test? Since most of the other functionalities already have tests?

**Comment by kilemensi** [comment]
> Looks all good @kilemensi But maybe we could add a test? Since most of the other functionalities already have tests?

Not sure if it's just on my end but tests in the current staging branch are already failing @esirK .

Screenshot from 2022-05-27 12-11-06

**Comment by kilemensi** [comment]
> > Looks all good 
> 
> Not sure if it's  ...
>

Found one of the issues @esirK: `collectstatic` must be run before running test since we're using `whitenoise.storage.CompressedManifestStaticFilesStorage`. Total errors down to **2** from _21_.

**Comment by esirK** [comment]
> Found one of the issues @esirK: `collectstatic` must be run before running test since we're using `whitenoise.storage.CompressedManifestStaticFilesStorage`. Total errors down to **2** from _21_.

Nice catch @kilemensi 
Also maybe confirm every step is as shown [here](https://github.com/OpenUpSA/wazimap-ng/blob/staging/.github/workflows/test.yml#L13)? Also trying it on my end.

**Comment by kilemensi** [comment]
> 

For the 2 failing tests... they both fail the exact same way i.e. `history.all().count()` returns 1 instead of 2. But if I change counting to just `history.count()`, it works.

Line: https://github.com/CodeForAfrica/wazimap-ng/blob/e2030bc118ec50ad800815f70d4e8a9b9b3966cb/tests/profile/admin_history/test_highlights_history.py#L42

Is this what you're experiencing on your end as well @esirK?

**Comment by esirK** [comment]
> collectstatic

Ola @kilemensi  yes I'm also getting same issue.

**Comment by esirK** [comment]
hold up on this a little @kilemensi

**Comment by esirK** [comment]
~Seems like I was testing with some old code. On staging the tests seems to work just file after the `collectstatic` on my end @kilemensi~
Never mind. I see you didn't change the count just the `all` bit

**Pull request merged**
